/*

 BASEMAPMETA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\ccann\Documents\Programming\C_Workspace\scavengers\sprite_files\tileMeta.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define baseMapMetaWidth 20
#define baseMapMetaHeight 18
#define baseMapMetaBank 0

extern unsigned char baseMapMeta[];

/* End of BASEMAPMETA.H */
