/*

 BASEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 9
   Tile set      : C:\Users\ccann\Documents\Programming\C_Workspace\scavengers\sprite_files\tile.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define baseMapWidth 10
#define baseMapHeight 9
#define baseMapBank 0

extern unsigned char baseMap[];

/* End of BASEMAP.H */
